/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiExecRouteImport } from './routes/api/exec'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecRoute = ApiExecRouteImport.update({
  id: '/api/exec',
  path: '/api/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agent' | '/api/exec' | '/api/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agent' | '/api/exec' | '/api/health'
  id: '__root__' | '/' | '/api/agent' | '/api/exec' | '/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiExecRoute: typeof ApiExecRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exec': {
      id: '/api/exec'
      path: '/api/exec'
      fullPath: '/api/exec'
      preLoaderRoute: typeof ApiExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiExecRoute: ApiExecRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
