/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiExecRouteImport } from './routes/api/exec'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPreviewStartRouteImport } from './routes/api/preview-start'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as PreviewSplatRouteImport } from './routes/preview.$'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecRoute = ApiExecRouteImport.update({
  id: '/api/exec',
  path: '/api/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewStartRoute = ApiPreviewStartRouteImport.update({
  id: '/api/preview-start',
  path: '/api/preview-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSplatRoute = PreviewSplatRouteImport.update({
  id: '/preview/$',
  path: '/preview/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview-start': typeof ApiPreviewStartRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview-start': typeof ApiPreviewStartRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview-start': typeof ApiPreviewStartRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/api/exec'
    | '/api/health'
    | '/api/preview-start'
    | '/api/sessions'
    | '/preview/$'
    | '/api/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/api/exec'
    | '/api/health'
    | '/api/preview-start'
    | '/api/sessions'
    | '/preview/$'
    | '/api/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/api/exec'
    | '/api/health'
    | '/api/preview-start'
    | '/api/sessions'
    | '/preview/$'
    | '/api/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiExecRoute: typeof ApiExecRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPreviewStartRoute: typeof ApiPreviewStartRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  PreviewSplatRoute: typeof PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exec': {
      id: '/api/exec'
      path: '/api/exec'
      fullPath: '/api/exec'
      preLoaderRoute: typeof ApiExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview-start': {
      id: '/api/preview-start'
      path: '/api/preview-start'
      fullPath: '/api/preview-start'
      preLoaderRoute: typeof ApiPreviewStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$': {
      id: '/preview/$'
      path: '/preview/$'
      fullPath: '/preview/$'
      preLoaderRoute: typeof PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface ApiSessionsRouteChildren {
  ApiSessionsIdRoute: typeof ApiSessionsIdRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiExecRoute: ApiExecRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPreviewStartRoute: ApiPreviewStartRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  PreviewSplatRoute: PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
